"""fixing errors with db

Revision ID: ea35e07707f4
Revises: 
Create Date: 2024-02-12 14:28:25.187835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea35e07707f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('species', sa.String(length=255), nullable=True),
    sa.Column('temperament', sa.String(length=255), nullable=True),
    sa.Column('muzzle', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets'))
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers'))
    )
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_trainings_pet_id_pets')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_trainings_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    op.drop_table('trainers')
    op.drop_table('pets')
    # ### end Alembic commands ###
